# Write your commit message in the imperative: “Fix bug” and not “Fixed bug” or “Fixes bug.” 
# This convention matches up with commit messages generated by commands like git merge and git revert.

# Stashing
git stash list # Show a list of stashes
git apply stash@{<index>} # Apply the stash from specific <index> position

# Committing
git --fixup <head> # Do a fixup commit over <head>
## Staging
git add -i # Perform interactive staging

# Logging
git log # Show a detail list of commits
git log --oneline # Show a one line list of commits

# Pushing
git push -u origin <branch> # Push and set upstream <branch> to track curent branch
git push -u origin <localBranch>:<remoteBranch> # Push <localBrach> and set upstream to call it <remoteBranch>

# Branching
## Renaming
git branch -m <new-name> # Rename curent branch to <new-name>
git branch -m <old-name>:<new-name> # Rename <old-name> branch to <new-name>
git push origin :<old-name> <new-name> # Delete <old-name> on remote and push <new-name>
git push origin -u <new-name> # Reset upstream to track <new-name>